templates:
- '/opt/prometheus/templates/*.tmpl'
route:
  group_by: [Alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-me
receivers:
-   name: email-me
    email_configs:
    - send_resolved: true
      to: osazizsg1@gmail.com
      headers:
        subject: '{{ template "email.custom.subject" . }}'
      html: '{{ template "email.custom.html" . }}'
      from: osazizsg1@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: "osazizsg1@gmail.com"
      auth_password: " password "
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']





